config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shopping_list_items

  get 'welcome/index'
	root 'welcome#index'

  resources :shopping_lists

  resources :items

  resources :shops

end

app/models/shopping_list_item.rb
class ShoppingListItem < ActiveRecord::Base
  belongs_to :shopping_list, class_name: 'ShoppingList', foreign_key: 'shopping_list_id'
  belongs_to :item
  validates :price, presence: true, numericality: true
  validates :quantity, presence: true, numericality: true
end

app/controllers/shopping_list_items_controller.rb
class ShoppingListItemsController < ApplicationController
  before_action :set_shopping_list_item, only: [:show, :edit, :update, :destroy]

  # GET /shopping_list_items
  # GET /shopping_list_items.json
  def index
    @shopping_list_items = ShoppingListItem.all
  end

  # GET /shopping_list_items/1
  # GET /shopping_list_items/1.json
  def show
  end

  # GET /shopping_list_items/new
  def new
    @shopping_list_item = ShoppingListItem.new
  end

  # GET /shopping_list_items/1/edit
  def edit
  end

  # POST /shopping_list_items
  # POST /shopping_list_items.json
  def create
    @shopping_list_item = ShoppingListItem.new(shopping_list_item_params)

    respond_to do |format|
      if @shopping_list_item.save
        format.html { redirect_to @shopping_list_item, notice: 'Shopping list item was successfully created.' }
        format.json { render :show, status: :created, location: @shopping_list_item }
      else
        format.html { render :new }
        format.json { render json: @shopping_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shopping_list_items/1
  # PATCH/PUT /shopping_list_items/1.json
  def update
    respond_to do |format|
      if @shopping_list_item.update(shopping_list_item_params)
        format.html { redirect_to @shopping_list_item, notice: 'Shopping list item was successfully updated.' }
        format.json { render :show, status: :ok, location: @shopping_list_item }
      else
        format.html { render :edit }
        format.json { render json: @shopping_list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopping_list_items/1
  # DELETE /shopping_list_items/1.json
  def destroy
    @shopping_list_item.destroy
    respond_to do |format|
      format.html { redirect_to shopping_list_items_url, notice: 'Shopping list item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping_list_item
      @shopping_list_item = ShoppingListItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopping_list_item_params
      params.require(:shopping_list_item).permit(:shopping_list_id, :item_id, :price, :quantity)
    end
end

app/helpers/shopping_list_items_helper.rb
module ShoppingListItemsHelper
end

app/views/shopping_list_items/_form.html.erb
<%= simple_form_for(@shopping_list_item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :shopping_list_id %>
    <%= f.input :item_id %>
    <%= f.input :price %>
    <%= f.input :quantity %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/shopping_list_items/edit.html.erb
<h1>Editing shopping_list_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @shopping_list_item %> |
<%= link_to 'Back', shopping_list_items_path %>

app/views/shopping_list_items/index.html.erb
<h1>All items in Existing Shopping Lists</h1>

<table>
  <thead>
    <tr>
      <th>Shopping list</th>
      <th>Item</th>
      <th>Price</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shopping_list_items.each do |shopping_list_item| %>
      <tr>
        <td><%= shopping_list_item.shopping_list_id %></td>
        <td><%= shopping_list_item.item_id %></td>
        <td><%= shopping_list_item.price %></td>
        <td><%= shopping_list_item.quantity %></td>
        <td><%= link_to 'Show', shopping_list_item %></td>
        <td><%= link_to 'Edit', edit_shopping_list_item_path(shopping_list_item) %></td>
        <td><%= link_to 'Destroy', shopping_list_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shopping list item', new_shopping_list_item_path %>
<a href= "/" >back</a>

app/views/shopping_list_items/new.html.erb
<h1>New shopping_list_item</h1>

<%= render 'form' %>

<%= link_to 'Back', shopping_list_items_path %>

app/views/shopping_list_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shopping list:</strong>
  <%= @shopping_list_item.shopping_list_id %>
</p>

<p>
  <strong>Item:</strong>
  <%= @shopping_list_item.item_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @shopping_list_item.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @shopping_list_item.quantity %>
</p>

<%= link_to 'Edit', edit_shopping_list_item_path(@shopping_list_item) %> |
<%= link_to 'Back', shopping_list_items_path %>