config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shopping_list_items

  get 'welcome/index'
	root 'welcome#index'

  resources :shopping_lists

  resources :items

  resources :shops

end

app/models/shopping_list.rb
class ShoppingList < ActiveRecord::Base
  has_many :shopping_list_items
  accepts_nested_attributes_for :shopping_list_items
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :set_shopping_list, only: [:show, :edit, :update, :destroy]

  # GET /shopping_lists
  # GET /shopping_lists.json
  def index
    @shopping_lists = ShoppingList.all
  end

  # GET /shopping_lists/1
  # GET /shopping_lists/1.json
  def show
  end

  # GET /shopping_lists/new
  def new
    @shopping_list = ShoppingList.new
  end

  # GET /shopping_lists/1/edit
  def edit
  end

  # POST /shopping_lists
  # POST /shopping_lists.json
  def create
    @shopping_list = ShoppingList.new(shopping_list_params)

    respond_to do |format|
      if @shopping_list.save
        format.html { redirect_to @shopping_list, notice: 'Shopping list was successfully created.' }
        format.json { render :show, status: :created, location: @shopping_list }
      else
        format.html { render :new }
        format.json { render json: @shopping_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shopping_lists/1
  # PATCH/PUT /shopping_lists/1.json
  def update
    respond_to do |format|
      if @shopping_list.update(shopping_list_params)
        format.html { redirect_to @shopping_list, notice: 'Shopping list was successfully updated.' }
        format.json { render :show, status: :ok, location: @shopping_list }
      else
        format.html { render :edit }
        format.json { render json: @shopping_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopping_lists/1
  # DELETE /shopping_lists/1.json
  def destroy
    @shopping_list.destroy
    respond_to do |format|
      format.html { redirect_to shopping_lists_url, notice: 'Shopping list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping_list
      @shopping_list = ShoppingList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopping_list_params
      params.require(:shopping_list).permit!
    end
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/views/shopping_lists/_form.html.erb
<%= simple_nested_form_for(@shopping_list) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :deadline %>
    <%= f.input :total_price %>
  </div>

  <div id="shopping_list_items">
    <%= f.fields_for :shopping_list_items do |ff| %>
      <%= ff.association :item %>
      <%= ff.input :price %>
      <%= ff.input :quantity %>
      <%= ff.link_to_remove "Remove" %>
    <% end %>
  </div>
  <%= f.link_to_add "Add Shopping List Item", :shopping_list_items %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/shopping_lists/edit.html.erb
<h1>Editing shopping_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @shopping_list %> |
<%= link_to 'Back', shopping_lists_path %>

app/views/shopping_lists/index.html.erb
<h1>Shopping Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Deadline</th>
      <th>Total price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shopping_lists.each do |shopping_list| %>
      <tr>
        <td><%= shopping_list.name %></td>
        <td><%= shopping_list.deadline %></td>
        <td><%= shopping_list.total_price %></td>
        <td><%= link_to 'Show', shopping_list %></td>
        <td><%= link_to 'Edit', edit_shopping_list_path(shopping_list) %></td>
        <td><%= link_to 'Destroy', shopping_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shopping list', new_shopping_list_path %>
<a href= "/" >back</a>

app/views/shopping_lists/new.html.erb
<h1>New shopping_list</h1>

<%= render 'form' %>

<%= link_to 'Back', shopping_lists_path %>

app/views/shopping_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shopping_list.name %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @shopping_list.deadline %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @shopping_list.total_price %>
</p>

<%= link_to 'Edit', edit_shopping_list_path(@shopping_list) %> |
<%= link_to 'Back', shopping_lists_path %>